---

- name: Ensure corosync.conf
  template:
    src: "{{ item }}"
    dest: /etc/corosync/corosync.conf
    backup: no
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - "corosync.conf.{{ ansible_os_family }}.j2"
    - "corosync.conf.default.j2"
  notify:
    - restart corosync
  tags:
    - corosync
    - config

- name: Create authkey file
  copy:
    content: "{{ corosync_authkey }}"
    dest: /etc/corosync/authkey
    backup: no
    owner: root
    group: root
    mode: 0644
  notify:
    - restart corosync
  when: corosync_authkey is defined

- meta: flush_handlers
