---

- name: Ensure corosync.conf
  template: src={{ item }} dest=/etc/corosync/corosync.conf backup=no owner=root group=root mode=0644
  with_first_found:
    - "corosync.conf.{{ ansible_os_family }}.j2"
    - "corosync.conf.default.j2"
  notify:
    - stop corosync services
    - restart corosync
    - start corosync services
  tags:
    - corosync
    - config

- name: Create authkey file
  copy:
    content: "{{ corosync_authkey }}"
    dest: /etc/corosync/authkey
    backup: no
    owner: root
    group: root
    mode: 0644
  when: corosync_authkey is defined

- name: Ensure corosync services
  corosync_service: name={{ item.service }} ver={{ item.ver }} user={{ item.user }} group={{ item.group }}
  with_items: services
  when: services is defined
  notify:
    - stop corosync services
    - restart corosync
    - start corosync services
  tags:
    - corosync
    - config
