---
- name: Ensure apt packages
  apt:
    pkg: '{{ item }}'
    state: '{{ corosync_pkg_state }}'
  tags:
    - corosync
    - setup
  with_items: '{{ corosync_packages }}'
  register: corosync_installed

- name: Deploy authkey
  set_fact: create_authkey=True
  when: corosync_installed|changed

# Workaround for https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829680
- name: Ensure directory uidgid.d exists for pcs package
  file:
    name: /etc/corosync/uidgid.d/
    state: directory
