---
- name: Ensure apt packages
  apt:
    pkg: '{{ item }}'
    state: '{{ corosync_pkg_state }}'
  tags:
    - corosync
    - setup
  with_items: corosync_packages
  register: corosync_installed

- name: Deploy authkey
  set_fact: create_authkey=True
  when: corosync_installed|changed

